### ISSUE TITLE
Powermail Fieldwrap Elements not hidden by powermail_cond

### ISSUE THREAD

**Issue by mesurinna** [einpraegsam/powermail_cond#10]
Hi all,

i have updated a TYPO3 Instance and now i a'm facing the problem that powermail_cond is not hiding fields. Input fields are correctly disabled but css style ="display:hidden" is not set to these fieldwraps as it should be. 

I checked the network stream and all is working fine. The page call of type=3132 is giving right fields with #action : "hide". But fields are visible.

Powermail_cond is working, cos when the condition switches the input disabled property to enabled.

Any hint for this problem? Can there be a conflict with other js code?

TYPO3 8.7.4
Powermail 3.22.1
Powermail_cond 3.4

**Comment by einpraegsam** [comment]
It works all as expected.
Did you test with original HTML-Templates and Partials?
