### ISSUE TITLE
All powermail forms throw TYPO3 Exception with powermail_cond installed

### ISSUE THREAD

**Issue by neotrace** [einpraegsam/powermail_cond#11]
Just encountered a problem on a large multilanguage multi-domain installation. Even without using a condition, just by having powermail_cond installed i get the following error on all pages with powermail forms when i submit:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function getForms() on null | Error thrown in file /var/www/servers/mydomain/html/typo3conf/ext/powermail_cond/Classes/Domain/Validator/ConditionAwareValidator.php in line 54. Requested URL: https://www.mydomain.com/en/contact/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=a2d59893a4d0f551dc4a063bc57d61eb

Additionally Chrome shows a ERR_BLOCKED_BY_XSS_AUDITOR page. If I disable powermail_cond, everything is fine. Unsure how to debug this or if this is even an issue with the extension or my configuration. Updated to most recent powermail and powermail_cond but no change.
Any ideas?

**Comment by einpraegsam** [comment]
Can you please send me your powermail and powermail_cond version number? Which TYPO3 version do you use?

**Comment by neotrace** [comment]
We are using powermail 4.3.2 with powermail_cond 3.5.1 in a typo3 7.6.23. Also it might be related to the language. I just discovered the forms in default language work as expected, only the translated forms throw the error.

**Comment by einpraegsam** [comment]
ok, seems that you have a field without a relation to a page. Nevertheless we should catch this possibility inConditionAwareValidator.

**Comment by einpraegsam** [comment]
I pushed a fix to develop branch. Can you please test for me if the bug is solved?

**Comment by neotrace** [comment]
Hi, I tested yesterday and the fix seems to work! Thank you for the quick support! 

What I don't get is what I did "wrong" or why I have a field without relation to a page?

I have a Condition, a Condition Container and Rules in a sysfolder directly beneath the page my powermail form is on since I cannot have the condition on the page directly.

**Comment by einpraegsam** [comment]
Thx, I just released 3.5.2 with the fix.
I'm not totally sure if the problem came from a misconfiguration or simply from a bug. Nevertheless it's good to catch this case.
