### ISSUE TITLE
Condition not working when ratio button is set to "Ja | 1 | *"

### ISSUE THREAD

**Issue by chequille** [einpraegsam/powermail_cond#14]
Hi Alex,
ok, at least I decided to make my form not on a multi step form because of powermail_cond.

But I found now, that the condition is not working when I did set a ratiobutton like

Ja | 1 
Nein | 2

i need the value set to 1 or 2 for further purposes, but doing like this the condition is not working anymore.
Only when the ratio button is simply set to 
Ja
Nein

Can you please check this.

Thanks and best regards,
Jürgen

**Comment by einpraegsam** [comment]
Hi Jürgen,

to save me a bit of testing time, because I'm rather sure that this works as expected: Do you listen to "1" or "2" in your rule instead of "Ja" and "Nein" when you change the value of your radiobuttons?
Can you please provide a screenshot of your condition with the rule?

Alex

**Comment by chequille** [comment]
Hi Alex,
it must have been too late yesterday evening :-)

It is working, sorry.
BR
Jürgen
