### ISSUE TITLE
Conditions with "unhide" rule always visible on iOS 11.3

### ISSUE THREAD

**Issue by kurzmela** [einpraegsam/powermail_cond#16]
Hi there, 
I'm using Powermail v5.5.0 with Powermail Conditions v4.1.1 in Typo3 8.7.11.
On iOS 11.3 `display: none;` isn't applied anymore to fields that should be hidden by default and only be opened with the unhide-condition. 
It's still working as expected in iOS 11.2.5.
Anyone else fighting this bug, any suggestions what to do?

**Comment by itgi** [comment]
This seems to be the same problem with the latest Safari on macOS. 
[https://github.com/einpraegsam/powermail_cond/issues/15](url)

**Comment by itgi** [comment]
@kurzmela No, I don't have a solution to this problem. Are you using file field in your form? This problem seems to appear only with file field.

**Comment by sascha-schieferdecker** [comment]
I can reproduce the problem too, the file upload seems to be the problem

**Comment by einpraegsam** [comment]
Duplicated to https://github.com/einpraegsam/powermail_cond/issues/15
