### ISSUE TITLE
Textarea mandatory

### ISSUE THREAD

**Issue by plojewski** [einpraegsam/powermail_cond#17]
Hi all,
I use powermail 3.17.0 and powermail_cond 3.2.1. I've created condition for textarea:
**if some checkbox is checked, then unhide textarea**
This textarea is mandatory and when I check the checkbox textarea's attribute "disabled" changes to "required". And it looks fine.
When I don't check the checkbox the textarea is hidden, but after click "Send" I've got powermail validation error ABOVE form: "Textarea is mandatory" generated by:
`<f:render partial="Misc/FormError" arguments="{_all}" />`
The question is, why powermail don't let to send form when textarea is hidden and disabled and has no "required" attribute in source (checkbox is not checked)?

**Comment by einpraegsam** [comment]
This old versions are not supported any more - sorry
