### ISSUE TITLE
AJAX loader icon

### ISSUE THREAD

**Issue by mcmz** [einpraegsam/powermail_cond#2]
Hi there,

is it be possible to integrate a simple loader icon for the ajax request?

I think that some users won't be aware of the moment when two overlapping fields have been toggled  – steered by a hide/unhide condition.

Maybe a .loader class could be shown initially and hides when ajax succeeds?

Many thx in advance and best regards
Martin

﻿

**Comment by einpraegsam** [comment]
Feel free to create a pull request for new features :)
