### ISSUE TITLE
Form not submitted with powermail 6.1.0

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail_cond#21]
Hi Alex, 

I today deployed powermail 6.1.0 and discvored that there is a bug with powermail_cond 5.0.0.
I use both extensions on TYPO3 8.7.17. 

The bug is:
If the user submits the form it gets the server validated messages that some of the fields (the undisplayed ones by conditions) have not been filled out.

I switched then back to powermail 6.0.0 and after this the form was successfully submitted.

Thank you for checking this out :)

Best regards
Christian

**Comment by Patta** [comment]
I can confirm this bug with TYPO3 8.7.18, powermail 6.1.0 and powermail_cond 5.0.0

**Comment by foobar13372** [comment]
I can confirm this, too.
 TYPO3 8.7.19
powermail 6.1.0
powermail_cond 5.0.0
