### ISSUE TITLE
Condition takes long with filled upload field

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail_cond#23]
PHP: 7.2.x
TYPO3: 8.7.18
powermail: 6.0.0
powermail_cond: 5.0.0
Browser: Latest Firefox, Chrome or Edge

Hi Alex, 

I have a multi-language form (DE and EN) with three conditions on radio elements and three upload fields. If the upload fields are empty the conditions work fast (i. e. the field(s) to be displayed appear quite immediately), but if one of the fields is filled with a file then it takes at least one minute until the field(s) to be displayed appear).

While investigating this I also found in the TYPO3 protocol that I got a warning about the function setTextFields in In2code\PowermailCond\Controller\ConditionController in case the argument to the function is null. After changing the type hint to "?Form" it seems to be fixed.

Maybe I can get back to this topic and send you a pull request if I think that I have a solution.

Cheers
Christian

**Comment by einpraegsam** [comment]
PR are always welcome but please respect also PHP 7.0

**Comment by chrisprog20** [comment]
Ok, thank you for your hint.
I think I have to clarify my report: When I did the fix by "?Form", only the warning in the protocol was removed, not the issue with the fields displaying very late if a upload field is filled.

I now measured 2 min 40s with two uploads fields filled (one with 2 KB, other with 16 MB).
