### ISSUE TITLE
Will condition testing in future be in frontend?

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail_cond#25]
Hi Alex, 

I have a question:

we encountered that if a form has a powermail condition (or more) 
that an ajax request is sent for every field in the form when focusout or change event takes place.
This results in a high server load (even until collapsing) if a lot of users are using this form parallely, for example after a newsletter with a link to the form has been sent out and e.g. 6000 users are visiting the form. My question now is, if it is planned to do the condition testing only in the frontend or do we have to create something by ourselves for such purposes?

Thank you for your answer in advance :)

Cheers
Christian

**Comment by einpraegsam** [comment]
We discussed a solution to not use every blur for a request in the past. But nevertheless there are no plans to integrate something like this in the near future.

**Comment by chrisprog20** [comment]
Hello Alex, 
thank you very much for your quick reply.
Best regards
Christian
