### ISSUE TITLE
[solution] powermail_cond at multiple language

### ISSUE THREAD

**Issue by Inovanet** [einpraegsam/powermail_cond#36]
I have the same form at 4 languages.

At the default it works, the other not.

For it to work i changed this Line:
In2code\PowermailCond\Controller\ConditionController : Line 56
$conditionContainer = $containerRepository->findOneByForm($form);
to
$conditionContainer = $containerRepository->findOneByForm($this->powermailArguments['mail']['form']);

**Comment by chriskrj** [comment]
Would be nice if this is included in next release...

**Comment by Hatecrew1337** [comment]
Better solution would be, the following statement.
$conditionContainer = $containerRepository->findByUid($form->getUid());

**Comment by fazzyx** [comment]
I have the same issue.
TYPO3 9.5.9 
powermail_cond 7.0.0
Mulitlanguage setup

The fix of mhirdes is working for me!

**Comment by nimayneb** [comment]
✅ Reviewed with TYPO3 9.5.13

Therefore, we add following lines in our `composer.json`:
```
"repositories": {
  "powermail-condition-forked-patch": {
    "type": "vcs",
    "url": "https://github.com/mhirdes/powermail_cond"
  }
}
```

Then:
```
$ composer clear
$ composer require in2code/powermail_cond dev-develop
```

Please push it to the next release. Thank you.

**Comment by taunusweb** [comment]
I have the same Issue and was happy to find this solution, but: It doesn't work (TYPO3 9.2.6 an powermail_cond 7.0.0). I've tested
$conditionContainer = $containerRepository->findOneByForm($this->powermailArguments['mail']['form']);
and 
$conditionContainer = $containerRepository->findByUid($form->getUid());
but both solutions didn't work... Any hints?

**Comment by lapierrec** [comment]
I have the same issue.
- TYPO3 10.7.16
- powermail_cond 8.0.1

The fix of mhirdes is working for me too. Hope this fix will be merged. :)

**Comment by kimchristiansen** [comment]
Same with powermail 8.4.1 powermail_cond 8.2.0 and TYPO3 10.4.22.
The fix by adding the powermail-condition-bugfix repository and changing the powermail_cond version to  dev-develop did not fix the problem.

**Comment by ax-ha** [comment]
Same over here. The condition is only working in one language. 
One form with multiple languages. 

Typo3 10.4.25 
Powermail 8.4.1
Powermail Conditions 8.2.2

I tried all variants of conditions/rules without success. How did you bring this to work?

**Comment by sbusemann** [comment]
Fixed in our Early Access Programm:  https://github.com/in2code-pro/powermail_cond/tree/pro 

Public release will follow.

More infos about the EAP: https://www.in2code.de/en/agency/typo3-extensions/early-access-program/
