### ISSUE TITLE
powermail_cond breaks the confirmation function if ajaxSubmit is enabled

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail_cond#38]
The form submit does not work if ajaxSubmit and the confirmation page is enabled and the user goes back to the form from the confirmation page. The form cannot be sent to the confirmation page again. Without powermail_cond or deactivated ajaxSubmit everything is fine. 

It seems that the with powermail_cond hidden fields are required but are hidden to the user if he comes back from the confirmation page. So the form can not be submitted again.

TYPO3 8.7.24
powermail 7.2.0
powermail_cond 7.0.0
PHP 7.3
composer mode

**Comment by mhirdes** [comment]
same problem here. any workaround?

**Comment by mhirdes** [comment]
Ok my workaround:

1. Include the PowermailCondition.js by yourself.

2. Add the following lines:

```
...
	$(document).ready(function() {
		$('form.powermail_form').each(function() {
			(new PowermailCondition(this)).ajaxListener();
		});
	});

        // begin changes:
	// @modified: trigger also for back from overview page
	$('.tx-powermail').on('submitted.powermail.form', function() {
		$('form.powermail_form').each(function() {
			(new PowermailCondition(this)).ajaxListener();
		});
	});
       // end changes:

})(jQuery);
```
