### ISSUE TITLE
?type=3132 Error

### ISSUE THREAD

**Issue by Kartoffl** [einpraegsam/powermail_cond#39]
Hello,
i use TYPO3 9.5.5, Powermail 7.3.0 and Powermail Conditions 7.0.0.

I can't get Powermail Conditions to work. 
I have a request form and some fields should pop up when the condition is met. But the fields are always showing and it isn't just working

The console throws me the following error:
`POST https://URL/index.php?id=3?type=3132 500 (Internal Server Error)`

and the error in TYPO3:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to In2code\PowermailCond\Controller\ConditionController::setTextFields() must be an instance of In2code\Powermail\Domain\Model\Form, null given, called in /www/htdocs/URL/typo3conf/ext/powermail_cond/Classes/Controller/ConditionController.php on line 53 | TypeError thrown in file /www/URL/typo3conf/ext/powermail_cond/Classes/Controller/ConditionController.php in line 69. Requested URL: https://URL/index.php?id=3?type=3132`

The Submit Button also doesn't work when Powermail Conditions is enabled.
If I disable Powermail Conditions, Powermail works just fine.

Could somebody help me to fix this problem?
Thanks

**Comment by Patta** [comment]
@Kartoffl you need a PageTypeEnhancer for type=3132
https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.5/Feature-86160-PageTypeEnhancerForMappingTypeParameter.html

**Comment by Kartoffl** [comment]
Oh well thanks for the reply, but I think this is too much for me, since i am really new to TYPO3. 
Would you mind to explain me how to achieve this? What do I need to write in the sites config.yaml?

**Comment by Patta** [comment]
Of course. Just add `powermail_cond.json: 3132` to the map of your PageTypeEnhancer in the site config file.

Example:
```
routeEnhancers:
    PageTypeSuffix:
        type: PageType
        map:
            powermail_cond.json: 3132
```
The filename of `powermail_cond.json` can by anything.

Maybe @einpraegsam can adapt the docs for this issue.

**Comment by Kartoffl** [comment]
@Patta Ok I inserted this into my config.yaml of the site but now I get the same error, but it is not showing ?type=3132 anymore but instead powermail_cond_json
`POST https://URL/de/anfrage/powermail_cond.json 500 (Internal Server Error)`

Is there anything else I need to do?
Thanks

**Comment by Patta** [comment]
Did you cleared all caches?

**Comment by agendartobias** [comment]
> Of course. Just add `powermail_cond.json: 3132` to the map of your PageTypeEnhancer in the site config file.
> 
> Example:
> 
> ```
> routeEnhancers:
>     PageTypeSuffix:
>         type: PageType
>         map:
>             powermail_cond.json: 3132
> ```
> 
> The filename of `powermail_cond.json` can by anything.
> 
> Maybe @einpraegsam can adapt the docs for this issue.

I works for me. TNX

**Comment by einpraegsam** [comment]
so, I will close this issue
