### ISSUE TITLE
Take few seconds to react

### ISSUE THREAD

**Issue by lapierrec** [einpraegsam/powermail_cond#43]
TYPO3: 8.7.27
powermail: 7.3.1
powermail_cond: 7.0.0

Hello,
I'm using powermail_cond to display some parts of the form after choosing an answer from a select. But, it takes few seconds to react, even to prepare the form before interaction. It's worse in a second language, it's take more than 5 seconds. Is it possible to reduce reaction time? Thanks!

Christiane

**Comment by einpraegsam** [comment]
If there are too many fields in a form, powermail_cond is getting slower and slower. This behaviour is tolerated at the moment.
