### ISSUE TITLE
Version compatible with TYPO3 v9 and v10

### ISSUE THREAD

**Issue by baschny** [einpraegsam/powermail_cond#44]
Hi, we love this extension!

Is there a plan to upgrade it to be compatible with TYPO3 v9 and v10 - and with that also to Powermail v8?

If not: why? If yes: any way we could support you on that?

**Comment by einpraegsam** [comment]
Yes of course there will be a version. If we need this extension for our customer projects, we are going to update it. If you need it a bit faster, just write me an email about your time plans and budgets.

**Comment by Patta** [comment]
fixed with 4cb3190

**Comment by sbusemann** [comment]
already solved
