### ISSUE TITLE
Bug Workspace/ PowermailCond

### ISSUE THREAD

**Issue by xbouillet** [einpraegsam/powermail_cond#46]
Hi,

PowermailCond and Workspaces seem to not work together.
We have a powermail form with PowerMail Cond conditions.
The conditions work correctly on this form.
But, if you switch to worspace mode, any conditions work.

We are using TYPO3 9.5.20 and powermailCond 7.0.0

Anyone have an idea?

**Comment by einpraegsam** [comment]
Hi, 

I'm sorry but as I already wrote on slack. Powermail and _cond does not support workspaces.

Greetings, Alex
