### ISSUE TITLE
Multilingual Conditions possible?

### ISSUE THREAD

**Issue by Shentao83** [einpraegsam/powermail_cond#56]
Hey there, is it possible to have multilingual conditions? At the moment I struggle a little bit with a form in several languages. When I have a condition with 2 or more rules with AND conjunction, I have not found a way to have this condition applied to several languages. It feels like they keep overriding each other. 

It seems like I have to try to rebuild the complete form in order to somehow avoid conditions with more than 1 rule.

**Comment by sbusemann** [comment]
Fixed in our Early Access Programm:  https://github.com/in2code-pro/powermail_cond/tree/pro 

Public release will follow.

More infos about the EAP: https://www.in2code.de/en/agency/typo3-extensions/early-access-program/
