### ISSUE TITLE
Powermail_conditions not working in "edit"-mode?

### ISSUE THREAD

**Issue by bendoo** [einpraegsam/powermail_cond#58]
Hello,

I got powermail_cond working for powermail (_pi1). However, it does not work for powermail_frontend (_pi2).
Is this supposed to work? Any reason why it does not?

Thanks in advance for any help on this.

**Comment by einpraegsam** [comment]
Yes, that's possible. powermail_cond does not work in every case (e.g. multistep, etc...). Would be a missing feature.
