### ISSUE TITLE
TYPO3 v11 Support?

### ISSUE THREAD

**Issue by jonashirschi** [einpraegsam/powermail_cond#65]
Hello,
Thank you for your great extension.
are there already plans to get powermail_cond compatible for TYPO3 v11?

**Comment by einpraegsam** [comment]
powermail_cond is already available for TYPO3 11 in the Early Access Program - see https://www.in2code.de/aktuelles/extension-support-fuer-typo3-version-11/
Of course there will be a community release as far as the new version is completely checked from our QS manager. For more details pls contact stefan.busemann@in2code.de
