### ISSUE TITLE
TYPO3 v11 dependency

### ISSUE THREAD

**Issue by emileblume** [einpraegsam/powermail_cond#68]
The ext_emconf.php still depends on older Powermail.

```
 'depends' => [
            'powermail' => '8.3.2-9.99.99',
```

Shouldn't this be something like this?

```
 'depends' => [
            'powermail' => '9.0.0-10.99.99',
```

**Comment by einpraegsam** [comment]
That is correct. While powermail 10 removed jQuery, we also plan to remove jQuery from powermail_cond. But in the first step, there is a version with jQuery for powermail 9. 
Next step then: Remove jQuery from powermail_cond and require powermail 10 
@sbusemann
