### ISSUE TITLE
Compatibillity with powermail > 9.99.99

### ISSUE THREAD

**Issue by mediaessenz** [einpraegsam/powermail_cond#69]
The current version of powemail_cond (9.0.3) is marked to be only compatible with powermail 8.3.2 - 9.99.99.

Therefore it is currently not possible to use the latest powermail version 10.4.1.

Is it really incompatible or is just the definition of the restriction/requirement wrong?

**Comment by sbusemann** [comment]
Yes it is a constraint, as Powermail 10 does not use jquery anymore. We are working on powermail_cond 10 atm.
