### ISSUE TITLE
Version compatible with Powermail ^10

### ISSUE THREAD

**Issue by MaximilianSchweiger** [einpraegsam/powermail_cond#70]
Hi,

I wanted to update powermail_cond on a TYPO3 v11. Here is also already powermail v10 installed. But it seems that the maximum supported version is 9.9.99. 
Is this something that slipped through or is the current version not yet compatible with powermail v10?

Error Log:
 Problem 1
    - in2code/powermail_cond[9.0.0, ..., 9.0.3] require in2code/powermail ^9.0 -> found in2code/powermail[9.0.0, 9.0.1, 9.0.2] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires in2code/powermail_cond 9.0.* -> satisfiable by in2code/powermail_cond[9.0.0, 9.0.1, 9.0.2, 9.0.3].

Thanks for your support,

Maximilian Schweiger

**Comment by sbusemann** [comment]
Powermail_cond uses still jquery - Powermail 10 not. We will provide a next version in our EAP Programm soon and will release it publicly end of ~q3.

Untill then you need to use Powermail 9 which works with powermail_cond
