### ISSUE TITLE
Dependency in version 9.0.3 is wrong

### ISSUE THREAD

**Issue by taurec76** [einpraegsam/powermail_cond#71]
Hello
In the ext_emconf the dependency for powermail is wrong, because it only includes versions up to 9.99.99, but powermail is currently at 10.4.2, so it could only be installed from TER if the risk exception is accepted.
No functional problems only an installation issue

**Comment by Patta** [comment]
#69

**Comment by einpraegsam** [comment]
Thx, duplicated ticket
