### ISSUE TITLE
Faulty powermail dependency constraint

### ISSUE THREAD

**Issue by Mainbird** [einpraegsam/powermail_cond#75]
Hi,

can you please fix the powermail dependency constraints inside composer.json and ext_emconf.php. 
The constrains are limited to:

https://github.com/einpraegsam/powermail_cond/blob/master/composer.json#L31
https://github.com/einpraegsam/powermail_cond/blob/master/ext_emconf.php#L14

So powermail 10.X isn't included.

Thank you in advance. :)

LG

**Comment by einpraegsam** [comment]
See #69 or #70 or #71
