### ISSUE TITLE
Exception "No powermail parameters are given" on translated pages

### ISSUE THREAD

**Issue by clemens7haar** [einpraegsam/powermail_cond#8]
On pages with translations and Powermail forms (powermail_cond active), I get the following error message:

`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: No powermail parameters are given - e.g. &tx_powermail_pi1[mail][form]=123 | Exception thrown in file /var/www/vhosts/my-domain/typo3conf/ext/powermail_cond/Classes/Controller/ConditionController.php in line 47. Requested URL: http://my-domain/en/page-with-form/`

The error is not shown, when I open the page with a click on the "view webpage" button in the backend. Then it opens with no speaking URL (http://my-domain/index.php?id=251&L=1). Maybe it has something to do with realurl?

A tip or solution would be great!

Best regards
Clemens

**Comment by einpraegsam** [comment]
Probably there are some redirects. I would check the browserconsole for errors and I would also check the AJAX requests in the browser.
Nevertheless, this seems to be a configuration issue in my eyes. That's why I'm going to close this issue for now.

**Comment by clemens7haar** [comment]
Thanks, you were right. The reason was an existing configuration for a pagetype in RealURL, that removed the type parameter of the AJAX request.
