### ISSUE TITLE
Condition status lost when user comes back from confirmation page

### ISSUE THREAD

**Issue by Patta** [einpraegsam/powermail_cond#81]
TYPO3 11.5.25
powermail 10.7.1
powermail_cond 10.1.1

Ajax submit and the confirmation page are enabled. 
My powermail form has fields that show and hide other fields with powermail_cond. 
When the user comes back to the form from the confirmation page, the conditions are lost.
All fields are visible that were previously hidden or visible.
In addition, the manipulation of visibility with conditions no longer works when the user comes back to the form from the confirmation page. 
No js errors are shown in the console.

With disabled ajax submit, everything works. 
Maybe this is an powermail issue?

**Comment by einpraegsam** [comment]
Hi Patrick,

powermail_cond does not work with confirmation page in powermail. And maybe also not with the AJAX request (not tested).
At the moment there are no plans to change it.

Greetings, Alex

**Comment by Patta** [comment]
Thanks for your feedback. Best regards
