### ISSUE TITLE
Copying forms together with condition containers breaks field relations

### ISSUE THREAD

**Issue by crealistiques** [einpraegsam/powermail_cond#9]
Given the case I have a standard Typo3 folder page type with one form and and a handful of condition records applied to the form. After copying the complete folder which means the form and all related records are copied, as also the condition container with its related records, the field relations inside the condition records are broken. They still point to the original form by uid. Even though I understand this behaviour and could imagine that it is not trivial for Typo3 to handle such relations, it would be really wonderful and an important improvement when these field relations would be set properly. Properly means that the field relations of the condition records point to the respective fields of the new copy of the original form. Thereby it would be very easy to duplicate a given form-condition pairing.

**Comment by einpraegsam** [comment]
Sorry, but this is not possible with TYPO3 core functionality
